#!/bin/sh

RED=$(printf '\033[0;31m')
GREEN=$(printf '\033[0;32m')
BLUE=$(printf '\033[0;34m')
NC=$(printf '\033[0m')

run_command() {
  echo "${BLUE}--------------- Running: $1 ---------------${NC}"
  if eval $1; then
    echo "${GREEN}--------------- ✔ $2 succeeded! ---------------${NC}"
    echo ""
  else
    echo "${RED}--------------- ✖ $2 failed! ---------------${NC}"
    exit 1
  fi
}

run_command "npm run test" "Jest tests"
